### ISSUE TITLE
Dictionary Tree

### ISSUE THREAD

**Issue by Zaheylu** [Zaheylu/Kana#14]
Data structure for storing and working with the vocabulary.
Possible structures:
- Perfect hashtable
- Trie / Radix tree ( / Succinct trie / Double-array trie )
- BK-tree
- Ternary search tree
- Directed acyclic word graph
- Suffix tree / PAT tree

**Comment by ShuboshaKuro** [comment]
I have to lookup some of these structures, but I can work on the storing if you want.

**Comment by ShuboshaKuro** [comment]
Patricia-Trie would be perfect for our purpose.
Directed acyclic word graph would be good as well, but since the japanese alphabet consists only of syllables, I prefer the first one.

**Comment by Zaheylu** [comment]
fixed in 48fe9e0b30650a60986686992e2bd3dd63db1b8c
